- website/index.html
Proguard configuration was broken because elements are being partly interpreted as HTML tags
> Fix broken proguard HTML

- butterknife/src/main/java/butterknife/ButterKnife.java
- butterknife/src/test/java/butterknife/ButterKnifeTest.java
- butterknife/src/test/java/butterknife/shadow/EditModeShadowView.java
Required views that were not found were calling a method that throws an
UnsupportedOperationException when in the Android Studio Previewer
(due to Previewer's use of BridgeResources). A check is now performed
to ensure that the view is not in Edit Mode before calling this method.
> Suppress unexpected exception in Previewer

- butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
- butterknife-compiler/src/main/java/butterknife/compiler/UnbinderBinding.java
- butterknife-compiler/src/test/java/butterknife/ButterKnife.java
- butterknife-compiler/src/test/java/butterknife/UnbinderTest.java
- butterknife-sample/src/main/AndroidManifest.xml
- butterknife-sample/src/main/java/com/example/butterknife/SimpleActivity.java
- butterknife/src/main/java/butterknife/ButterKnife.java
- website/index.html
This address the issue raised in #390. Allows unbinders to inherit form parent `ViewBinder.ViewUnbinder`'s.
__Changes:__
* Renamed `ButterKnife.Unbinder` -> `ButerKnife.ViewUnbinder`.
* By default only the top level Unbinder (no parent case) overrides the `ButterKnife.ViewUnbinder#unbind()` method, making it final. The actual unbindings happen in `generated_source$$ViewBinder.Unbinder#unbind(T)`, this allows all child unbinders to override it not braking the expected behaviour. 
* For every "potential" parent unbinder we generate 2 protected helper methods in the `ViewBinder` class.
* Each child `ViewBInder` overrides at at-least the `createUnbinder` method providing he's "extended" Unbinder. 
* If a child also binds an unbinder, `accessUnbinder` will be overriden, but will be called only …
> Support for unbinder inheritance.

- butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
- butterknife-compiler/src/test/java/butterknife/BindArrayTest.java
- butterknife-compiler/src/test/java/butterknife/BindBitmapTest.java
- butterknife-compiler/src/test/java/butterknife/BindBoolTest.java
- butterknife-compiler/src/test/java/butterknife/BindColorTest.java
- butterknife-compiler/src/test/java/butterknife/BindDimenTest.java
- butterknife-compiler/src/test/java/butterknife/BindDrawableTest.java
- butterknife-compiler/src/test/java/butterknife/BindIntTest.java
- butterknife-compiler/src/test/java/butterknife/BindStringTest.java
- butterknife-compiler/src/test/java/butterknife/BindViewTest.java
- butterknife-compiler/src/test/java/butterknife/BindViewsTest.java
- butterknife-compiler/src/test/java/butterknife/OnCheckedChangedTest.java
- butterknife-compiler/src/test/java/butterknife/OnClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnEditorActionTest.java
- butterknife-compiler/src/test/java/butterknife/OnFocusChangeTest.java
- butterknife-compiler/src/test/java/butterknife/OnItemClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnItemLongClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnItemSelectedTest.java
- butterknife-compiler/src/test/java/butterknife/OnLongClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnPageChangeTest.java
- butterknife-compiler/src/test/java/butterknife/OnTextChangedTest.java
- butterknife-compiler/src/test/java/butterknife/OnTouchTest.java
- butterknife-compiler/src/test/java/butterknife/UnbinderTest.java
- butterknife-sample/src/main/java/com/example/butterknife/SimpleAdapter.java
- butterknife-sample/src/main/java/com/example/butterknife/unbinder/F.java
This switches each generated class to directly instantiate its unbinder (if needed, or the nearest parent's) and use static dispatch upward for binding views.
> Improve performance of generated code (part 1).

- build.gradle
- butterknife-compiler/build.gradle
- butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
Remove the need to know about subclasses or parent types beyond the immediate. Type hierarchies are small so we can iterate them on-demand.
> Clean up internals of how BindingClass generates code.

- build.gradle
- butterknife-compiler/build.gradle
- butterknife-sample/src/test/java/com/example/butterknife/SimpleActivityTest.java
- butterknife-sample/src/test/java/com/example/butterknife/SimpleAdapterTest.java
- butterknife-sample/src/test/java/com/example/butterknife/unbinder/UnbinderTest.java
- butterknife-sample/src/test/resources/robolectric.properties
- butterknife/src/test/java/butterknife/ButterKnifeTest.java
- butterknife/src/test/java/butterknife/internal/FinderTest.java
Robolectric 3.1 removes its transitive dependency on `com.google.android:support-v4:r7` so I had to include it manually. Unfortunately we can't use the `deps.supportv4` dependency as the Gradle Java plugin does not support AAR dependencies.
> Update Robolectric to 3.1

- butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
- butterknife-compiler/src/test/java/butterknife/BindViewTest.java
- butterknife-compiler/src/test/java/butterknife/internal/Finder.java
- butterknife/src/main/java/butterknife/internal/Finder.java
Follow-up to #655.
Change `Finder.castView` to expect `Class<T>` as argument and use `cls.cast(view)` instead of `(T) view`. This code path was also untested previously, so I added a simple test for this case.
Finally change `findOptionalViewAsType` and `findRequiredViewAsType` to re-use this method.
> Change & reuse Finder.castView(…)

- butterknife-gradle-plugin/src/main/groovy/butterknife/plugin/ButterKnifePlugin.groovy
On _Windows environment_ the following statement throws an exception:
```javascript
packageForR.replaceAll('\\.', File.separator)
```
``` 
Caused by: java.lang.IllegalArgumentException: character to be escaped is missing
at java_lang_String$replaceAll$8.call(Unknown Source)
at butterknife.plugin.ButterKnifePlugin$_apply_closure1$_closure2$_closure3$_closure4.doCall(ButterKnifePlugin.groovy:30)
at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:554)
at org.gradle.api.internal.AbstractTask$ClosureTaskAction.execute(AbstractTask.java:535)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskEx …
```
> Fix unescaped File.separator on Windows environment (butterknife-gradle-plugin).

- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
This guards against #670 in which case butterknife falls back to legacy behavior of using hardcoded constants in generated code instead of `R` references.
> Guard for null tree when scanning for R Classes

- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
- checkstyle.xml
This allows use with the Jack compiler.
Closes #673.
> Ignore Trees failures and fall back to numerical IDs.

- butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
- butterknife-compiler/src/test/java/butterknife/BindArrayTest.java
- butterknife-compiler/src/test/java/butterknife/BindBitmapTest.java
- butterknife-compiler/src/test/java/butterknife/BindBoolTest.java
- butterknife-compiler/src/test/java/butterknife/BindColorTest.java
- butterknife-compiler/src/test/java/butterknife/BindDimenTest.java
- butterknife-compiler/src/test/java/butterknife/BindDrawableTest.java
- butterknife-compiler/src/test/java/butterknife/BindFloatTest.java
- butterknife-compiler/src/test/java/butterknife/BindIntTest.java
- butterknife-compiler/src/test/java/butterknife/BindStringTest.java
- butterknife-compiler/src/test/java/butterknife/BindViewTest.java
- butterknife-compiler/src/test/java/butterknife/BindViewsTest.java
- butterknife-compiler/src/test/java/butterknife/OnCheckedChangedTest.java
- butterknife-compiler/src/test/java/butterknife/OnClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnEditorActionTest.java
- butterknife-compiler/src/test/java/butterknife/OnFocusChangeTest.java
- butterknife-compiler/src/test/java/butterknife/OnItemClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnItemLongClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnItemSelectedTest.java
- butterknife-compiler/src/test/java/butterknife/OnLongClickTest.java
- butterknife-compiler/src/test/java/butterknife/OnPageChangeTest.java
- butterknife-compiler/src/test/java/butterknife/OnTextChangedTest.java
- butterknife-compiler/src/test/java/butterknife/OnTouchTest.java
- butterknife-compiler/src/test/java/butterknife/RClassTest.java
- butterknife-compiler/src/test/java/butterknife/UnbinderTest.java
This ensures that if they're used directly they're used from the proper thread.
> Add @UiThread to generated class constructors.

- build.gradle
Google deleted 24.2.0 out from under us. Thanks, Obama.
> Support libraries to 24.2.1.

- checkstyle.xml
For example:
word 'foreground' don't pass checkstyle
> Fix RegexpSingleline in checkstyle rules

- build.gradle
- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
- butterknife/src/test/java/butterknife/OnTextChangedTest.java
Fix #782 
- Add checking to listener method parameter to allow using subtype of original method's type only when the parameter is subtype of view.
- Add testcase in OnTextChangedTest.java
> Fix listener method type checking

- build.gradle
- butterknife-lint/src/main/java/butterknife/lint/InvalidR2UsageDetector.java
- butterknife-lint/src/test/java/butterknife/lint/InvalidR2UsageDetectorTest.java
I was able to confirm that the ButterKnife custom lint was the reason for this issue with Retrolambda to resurface: https://github.com/evant/gradle-retrolambda/issues/96
Apparently, if you have any custom lint rules using the old lombok API, the linter will run it twice, both with the old and with the new API, making the lint slower and also causing it to spit enourmous amounts of stacktraces due to the retrolambda incompatibility, as described in the issue linked above.
Unfortunately, the custom lombok ast build stopped working for reasons I can't understand, but fixing the butterknife linter should be enough to have the linter stop spitting stacktraces (as long as you don't have any other custom lint rules using the lombok api).
This PR migrates the custom R2 lint rule to the new PSI …
> [Lint] Migrate to new PSI API

- butterknife-annotations/src/main/java/butterknife/BindAnim.java
- butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java
- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
- butterknife-compiler/src/main/java/butterknife/compiler/FieldAnimationBinding.java
- butterknife/src/test/java/butterknife/BindAnimTest.java
Related to the request in #870, this PR adds a new `@BindAnim` annotation, with which `Animation` resources can be bound to fields.
Example Usage:
```java
public class Test {
@BindAnim(R.anim.fade_in)
Animation fadeIn;
}
```
Generated code uses `AnimationUtils#loadAnimation` to retrieve the resource.
> Added support for binding animation resources

- build.gradle
- butterknife-annotations/build.gradle
- butterknife-compiler/build.gradle
- butterknife-gradle-plugin/build.gradle
- butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt
- butterknife-integration-test/build.gradle
- butterknife-lint/build.gradle
- butterknife/build.gradle
- gradle/wrapper/gradle-wrapper.properties
- sample/app/build.gradle
- sample/library/build.gradle
- settings.gradle
- Bump to Gradle 4.0-M1
- Bump to AGP 3.0.0-alpha8
- Update dependency configuration syntax
- Tell Robolectric to include Android resources in tests
- Update plugin usage of variant api
> Update to AGP 3.0.0a8

- butterknife-compiler/build.gradle
These come from the Google repo now.
> Remove hacky SDK repo adding for support-annotations.

- .travis.yml
- butterknife-integration-test/build.gradle
- butterknife/build.gradle
Also since we're splitting the commands, don't run lint release checks during compilation since the 'check' task will do a full lint run anyway.
> Speed up builds by racing emulator start.

- .travis.yml
Looks like the Trusty Linux distribution isn't quite as complete as its Precise predecessor.
1) SDK Tools dir doesn't contain avdmanager, lint, etc.
```
$ ls /usr/local/android-sdk/tools/bin
sdkmanager
```
2) Travis no longer seems to recognize the configuration in the android.components section for system images
3) The emulator command has moved from tools to the sdk base dir.
This PR reflects and works around these limitations.
> Use avdmanager instead of deprecated android command

- build.gradle
- butterknife-lint/build.gradle
- butterknife/build.gradle
* Update AGP and Lint to beta6.
* Update lint dependencies to 'compileOnly' configuration
* Replace lintrules plugin with built-in lint configuration
* Update to new Lint Registry for UAST support
* Replace Gradle plugins repo with jcenter
See https://issuetracker.google.com/issues/62914381#comment23
> Fix custom lint checks

- butterknife/build.gradle
While learning the difference between api/implementation I noticed that:
-  `butterknife-annotations` exposes `deps.support.annotations`
- `butterknife` depends on `butterknife-annotations`
- `butterknife` has `implementation deps.support.annotations`
So, `butterknife` doesn't need `deps.support.annotations`.
Does it make sense?
> Removed support.annotations dependency from Butterknife

- .travis.yml
As mentioned, can be removed since 3.0.0 of the plugin is out. I figured this is a good thing to do here since others might use this `travis.yml` as a template
> Remove android:components block

- build.gradle
- butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt
Use `BaseVariant.getApplicationId()` instead of `ProcessAndroidResources.getOriginalApplicationId()` which was moved to an internal class `LinkApplicationAndroidResourcesTask` in `AGP 3.1.0-alpha07`
> Use `BaseVariant.getApplicationId()` to make ButterknifePlugin compatible with AGP 3.1.0-alpha07

- butterknife-gradle-plugin/build.gradle
- butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt
- butterknife-gradle-plugin/src/test/AndroidManifest.xml
- butterknife-gradle-plugin/src/test/build.gradle
- butterknife-gradle-plugin/src/test/fixtures/suffix_parsed_properly/src/main/java/butterknife/test/ButteryActivity.java
- butterknife-gradle-plugin/src/test/fixtures/suffix_parsed_properly/src/main/res/layout/activity_layout.xml
- butterknife-gradle-plugin/src/test/java/butterknife/plugin/AndroidHome.kt
- butterknife-gradle-plugin/src/test/java/butterknife/plugin/BuildFilesRule.kt
- butterknife-gradle-plugin/src/test/java/butterknife/plugin/FixturesTest.kt
- gradle/wrapper/gradle-wrapper.properties
We don't want to use the applicationId to find the location of the
R.java file because the R.java file's location is based on the package
name not the applicationId.
The applicationId can change based on the variant, but the R.java file's
location will not change.
Added some tests to make sure this works based on the FixturesTest in
SQLDelight.
Fixes #1177
> Parse manifest to determine package name.

- website/index.html
https://github.com/JakeWharton/butterknife/blob/master/CHANGELOG.md#version-880-2017-08-04
> Deprecate the findById methods. Compile against API 26 and use the normal findViewById for the same functionality.
(Exactly the same as #1168, same branch, same base, GitHub's "change base" doesn't seem to work, sorry about the mess there.)
> ButterKnife.findById methods are deprecated, don't encourage using them

- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
This guarantees that every id we are trying to lookup always has a `CodeBlock` representation
> Simplify resourceId lookup logic a bit

- butterknife/src/main/java/butterknife/ButterKnife.java
No need for the extra stack frame when the signatures are the same and the latter simply delegated to the former.
> Inline createBinding into bind(Object, View)

- butterknife-annotations/src/main/java/butterknife/BindString.java
- butterknife-annotations/src/main/java/butterknife/BindView.java
- butterknife-annotations/src/main/java/butterknife/BindViews.java
- butterknife-integration-test/build.gradle
- butterknife-integration-test/proguard.pro
- butterknife-reflect/build.gradle
- butterknife-reflect/gradle.properties
- butterknife-reflect/proguard-rules.txt
- butterknife-reflect/src/main/AndroidManifest.xml
- butterknife-reflect/src/main/java/butterknife/ButterKnife.java
- butterknife-reflect/src/main/java/butterknife/CompositeUnbinder.java
- butterknife-reflect/src/main/java/butterknife/FieldUnbinder.java
- settings.gradle
This is for IDE builds where annotation processing can dramatically slow down iteration time. Right now only BindView, BindViews, and BindString work as those are the bindings used by the integration test.
> Start entirely reflection-backed module

- README.md
BK 10's plugin requires com.android.tools.build:gradle:3.1.4 and the google repo should be added to the buildscript's repos.
BK 10 also requires compileSDK 28, I don't know where the docs should reflect this.
> Add the google repo

- butterknife-integration-test/build.gradle
- butterknife-reflect/src/main/java/butterknife/ButterKnife.java
- butterknife-runtime/build.gradle
- butterknife/build.gradle
Almost all of the nullability annotations don't have runtime retention so this only causes problems. Also you'll get an NPE and it'll be obvious anyway, it just won't be eager.
> Remove enforcement of required views in reflection backend

- website/index.html
Currently, the website shows this as an example of how to bind a `float` dimen:
```java
@BindDimen(R.dimen.spacer) Float spacer; // int (for pixel size) or float (for exact value) field
```
Using `Float` as the type for the `spacer` variable will cause the following error:
```
error: @BindDimen field type must be 'int' or 'float'.
```
The type for the `spacer` variable here should be the primitive `float` type like this:
```java
@BindDimen(R.dimen.spacer) float spacer; // int (for pixel size) or float (for exact value) field
```
> Fix BindDimen Float Example on Website

- butterknife-runtime/src/main/java/butterknife/internal/Utils.java
- butterknife-runtime/src/test/java/butterknife/UtilsTest.java
Instead of creating and copying a subset of the array manually. This also expands the tests to ensure the original instance is returned unmodifed when no nulls are present.
> Use copyOfRange helper

- butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java
- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
- butterknife-runtime/src/test/java/butterknife/ClasspathParentBindTest.java
This commit expands search for parent bindings by examining all
superclasses of types processed in the current round. Bindings found
in the classpath will not be generated, but information they contain
will be used when generating bindings for the current round of processing.
Test: ClasspathParentBindTest
Closes #808. Closes #1466.
> Add support for finding parent bindings in classpath

- build.gradle
- butterknife-compiler/build.gradle
- butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java
- butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
This commit adds incremental annotation processing support
to Butterknife. More specifically, it makes Butterknife an
isolating annotation processor. More information about what
this means can be found at
https://docs.gradle.org/current/userguide/java_plugin.html#isolating_annotation_processors.
Closes #1230
> Add support for incremental annotation processing

- butterknife-gradle-plugin/src/main/java/butterknife/plugin/R2Generator.kt
This allows `R2Generator` tasks to use the Gradle build cache to share their outputs.
> Make R2Generator task cacheable

- butterknife-gradle-plugin/build.gradle
- butterknife-gradle-plugin/src/main/java/butterknife/plugin/FinalRClassBuilder.kt
- butterknife-gradle-plugin/src/main/java/butterknife/plugin/ResourceSymbolListReader.kt
- butterknife-gradle-plugin/src/test/build.gradle
- butterknife-gradle-plugin/src/test/java/butterknife/plugin/FixturesTest.kt
- butterknife-gradle-plugin/src/test/resources/fixtures/R2.java
- gradle/gradle-mvn-push.gradle
These values are meaningless. We only need them to be unique which is trivially achievable with a counter.
This change is required, however, because AGP 3.6 will stop generating ID values in library projects. All values are set to 0 which obviously will prevent Butter Knife from correctly performing the reverse mapping from R2 value back to name.
Closes #1549.
> Use fake ID values for R2

- butterknife-integration-test/src/androidTest/java/com/example/butterknife/functional/OnClickTest.java
- butterknife-integration-test/src/androidTest/java/com/example/butterknife/functional/ViewTree.java
- butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java
Avoid `DebouncingOnClickListener` static field `enabled` staying in `false` state. 
Fixes #1619
> Avoid all @OnClick events may not working

- butterknife-reflect/src/main/java/butterknife/ButterKnife.java
Looks like we aren't passing through the MotionEvent.class when using butterknife-reflect.
> java.lang.IllegalArgumentException: Wrong number of arguments; expected 2, got 1
While this shouldn't effect any production builds since folks shouldn't be using this in prod, it can cause `@OnTouch` annotations to crash when using in debug builds for users that use it.
> Fix IllegalArgumentException in @Touch in butterknife-reflect
