JakeWharton/butterknife

butterknife/src/main/java/butterknife/ButterKnife.java, butterknife/src/test/java/butterknife/ButterKnifeTest.java
=> Filter missing views from InjectViews lists.

website/index.html
Diamond operator cannot be used with anonymous inner classes, the third parameter of `ButterKnife.apply` with `View.Alpha` has Float type and therefore accepts float and not int.
=> Fix website code for view lists.

CHANGELOG.md
=> Proguard instructions to change log.

butterknife/src/main/java/butterknife/ButterKnife.java
=> Remove explicit array allocation by leaning on copy.

butterknife/src/main/java/butterknife/ButterKnife.java
trivial fix.
Rename resource binding classes and R._integer*_ class
=> Fix Javadoc

butterknife/src/main/java/butterknife/BindStringArray.java, butterknife/src/main/java/butterknife/internal/ButterKnifeProcessor.java, butterknife/src/test/java/butterknife/internal/BindStringArrayTest.java
=> Support binding string array resources.

butterknife/src/test/java/butterknife/internal/BindArrayTest.java
=> Remove unused imports from tests.

butterknife/src/main/java/butterknife/BindBitmap.java, butterknife/src/main/java/butterknife/internal/BindingClass.java, butterknife/src/main/java/butterknife/internal/ButterKnifeProcessor.java, butterknife/src/main/java/butterknife/internal/FieldBitmapBinding.java, butterknife/src/test/java/butterknife/internal/BindBitmapTest.java
=> Support `@BindBitmap` annotation

butterknife/src/main/java/butterknife/ButterKnife.java, butterknife/src/main/java/butterknife/internal/BindingClass.java, butterknife/src/main/java/butterknife/internal/ButterKnifeProcessor.java, butterknife/src/main/java/butterknife/internal/MethodViewBinding.java, butterknife/src/main/java/butterknife/internal/ViewBindings.java, butterknife/src/test/java/butterknife/internal/AllTheThingsTest.java, pom.xml
=> Use Java 7 language level.

website/ide-eclipse.html
Added one step - hitting Properties option
=> Typo - Missing step

butterknife/src/main/java/butterknife/ButterKnife.java, butterknife/src/test/java/butterknife/ButterKnifeTest.java
=> Return View from view binders.

butterknife-sample/build.gradle, butterknife/build.gradle, butterknife/proguard-rules.txt, website/index.html
Closes #347!
I'd suggest to update the section about ProGuard on the website right before or after the release to avoid tons of questions "why it does not work" :)
=> Package ProGuard rules into the aar

butterknife/src/main/java/butterknife/ButterKnife.java, butterknife/src/test/java/butterknife/ButterKnifeTest.java
Closes #332
Opted not to do this for properties and setters since it's unlikely that the same value would apply to multiple setters. Open to suggestions on it though
=> Accept vararg Actions in apply calls

build.gradle, butterknife-compiler/build.gradle, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
=> Use SuperficialValidator to avoid broken elements.

butterknife-annotations/build.gradle, butterknife-annotations/src/main/java/butterknife/Bind.java, butterknife-annotations/src/main/java/butterknife/BindArray.java, butterknife-annotations/src/main/java/butterknife/BindBitmap.java, butterknife-annotations/src/main/java/butterknife/BindBool.java, butterknife-annotations/src/main/java/butterknife/BindColor.java, butterknife-annotations/src/main/java/butterknife/BindDimen.java, butterknife-annotations/src/main/java/butterknife/BindDrawable.java, butterknife-annotations/src/main/java/butterknife/BindInt.java, butterknife-annotations/src/main/java/butterknife/BindString.java, butterknife-annotations/src/main/java/butterknife/OnCheckedChanged.java, butterknife-annotations/src/main/java/butterknife/OnClick.java, butterknife-annotations/src/main/java/butterknife/OnEditorAction.java, butterknife-annotations/src/main/java/butterknife/OnFocusChange.java, butterknife-annotations/src/main/java/butterknife/OnItemClick.java, butterknife-annotations/src/main/java/butterknife/OnItemLongClick.java, butterknife-annotations/src/main/java/butterknife/OnItemSelected.java, butterknife-annotations/src/main/java/butterknife/OnLongClick.java, butterknife-annotations/src/main/java/butterknife/OnPageChange.java, butterknife-annotations/src/main/java/butterknife/OnTextChanged.java, butterknife-annotations/src/main/java/butterknife/OnTouch.java, butterknife-compiler/build.gradle
...with a gross hack!
Closes #144.
=> Add support annotations to bind/listener annotations.

butterknife/src/main/java/butterknife/ButterKnife.java, butterknife/src/test/java/butterknife/ButterKnifeTest.java
=> Apply for arrays.

build.gradle, butterknife-annotations/src/main/java/butterknife/Unbinder.java, butterknife-compiler/src/test/java/butterknife/UnbinderTest.java, butterknife/src/main/java/butterknife/internal/Utils.java
=> Support minSdkVersion 8. Whaaaaaaa?

butterknife/build.gradle
This way it'll also work in debug and not only in release mode
=> Fix consumerProguardFiles by moving it to defaultConfig

butterknife-compiler/src/test/java/butterknife/internal/DebouncingOnClickListener.java, butterknife/src/main/java/butterknife/internal/DebouncingOnClickListener.java
Removes 1 method to 130 from 131.
=> Remove creation of synthetic accessor methods.

javadoc/butterknife/BindBool.html, javadoc/butterknife/BindColor.html, javadoc/butterknife/BindDimen.html, javadoc/butterknife/BindDrawable.html, javadoc/butterknife/BindInt.html, javadoc/butterknife/BindString.html, javadoc/butterknife/ButterKnife.html
Is this the correct way to update the javadoc for this project?
[deploy_website.sh](https://github.com/JakeWharton/butterknife/blob/master/deploy_website.sh) would overwrite the changes made in this patch unless the javadoc jar is created and uploaded to repository.sonatype.org
=> Replace annotations with Resource prefix with Bind prefix

.travis.yml
=> Remove explicit license.

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/test/java/butterknife/BindViewTest.java
=> Emit less methods for final types.

README.md
=> Missing mavenCentral() repository

butterknife/proguard-rules.txt
=> Change Proguard rules to be less matchy

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/test/java/butterknife/BindViewTest.java
=> Do not guess TypeName when we know class name and package.

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java, butterknife-compiler/src/test/java/butterknife/BindViewTest.java
=> Generate overloaded binding mechanism when parent bindings present.

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
bindToTarget method will never need a finder.
=> Small tweaks to code generator.

README.md
The process of adding the 8+ version to an android project wasn't clear to me so I made clear where to put which part.
=> Updated download section

.travis.yml, build.gradle
@JakeWharton Update to Android 24 since it is now out
=> Update to android 24

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java
- Will add tests soon to cover all annotations
=> Fix generated code

butterknife-compiler/src/test/java/butterknife/BindViewTest.java, butterknife-compiler/src/test/java/butterknife/BindViewsTest.java, butterknife-compiler/src/test/java/butterknife/ButterKnife.java, butterknife-compiler/src/test/java/butterknife/OnClickTest.java, butterknife-compiler/src/test/java/butterknife/OnItemClickTest.java, butterknife-compiler/src/test/java/butterknife/OnTouchTest.java, butterknife-compiler/src/test/java/butterknife/UnbinderTest.java
=> Eliminate Joiner in tests

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java, butterknife-compiler/src/main/java/butterknife/compiler/Id.java
- This will prevent anyone from accidentally using toString on `Id`
=> Do not allow toString() operation on Id

butterknife-compiler/src/test/java/butterknife/BindArrayTest.java, butterknife-compiler/src/test/java/butterknife/BindBitmapTest.java, butterknife-compiler/src/test/java/butterknife/BindBoolTest.java, butterknife-compiler/src/test/java/butterknife/BindColorTest.java, butterknife-compiler/src/test/java/butterknife/BindDimenTest.java, butterknife-compiler/src/test/java/butterknife/BindDrawableTest.java, butterknife-compiler/src/test/java/butterknife/BindIntTest.java, butterknife-compiler/src/test/java/butterknife/BindStringTest.java, butterknife-compiler/src/test/java/butterknife/BindViewTest.java, butterknife-compiler/src/test/java/butterknife/BindViewsTest.java, butterknife-compiler/src/test/java/butterknife/OnCheckedChangedTest.java, butterknife-compiler/src/test/java/butterknife/OnClickTest.java, butterknife-compiler/src/test/java/butterknife/OnEditorActionTest.java, butterknife-compiler/src/test/java/butterknife/OnFocusChangeTest.java, butterknife-compiler/src/test/java/butterknife/OnItemClickTest.java, butterknife-compiler/src/test/java/butterknife/OnItemLongClickTest.java, butterknife-compiler/src/test/java/butterknife/OnItemSelectedTest.java, butterknife-compiler/src/test/java/butterknife/OnLongClickTest.java, butterknife-compiler/src/test/java/butterknife/OnPageChangeTest.java, butterknife-compiler/src/test/java/butterknife/OnTextChangedTest.java, butterknife-compiler/src/test/java/butterknife/OnTouchTest.java, butterknife-compiler/src/test/java/butterknife/RClassTest.java, butterknife-compiler/src/test/java/butterknife/UnbinderTest.java, butterknife/src/test/java/butterknife/ButterKnifeTest.java
I have no idea if you want to merge this, but IMO this makes sense as we want to generate code that compiles without warnings.
If you are fine with these changes, I'll squash the different commits into a single one.
=> Use compilesWithoutWarnings in tests

build.gradle
=> Update support libs

.travis.yml, build.gradle
=> Update build tools

butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/test/java/butterknife/BindViewTest.java, butterknife-compiler/src/test/java/butterknife/OnItemClickTest.java
=> Allow anyone to bind listeners to root view.

butterknife-annotations/src/main/java/butterknife/BindFloat.java, butterknife-compiler/src/main/java/butterknife/compiler/BindingClass.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldResourceBinding.java, butterknife-compiler/src/test/java/butterknife/BindFloatTest.java, butterknife-compiler/src/test/java/butterknife/internal/Utils.java, butterknife/src/main/java/butterknife/internal/Utils.java
=> Add @BindFloat annotation.

.travis.yml, build.gradle
@JakeWharton Update build tools to 24.0.2
=> Update build tools to 24.0.2

build.gradle, butterknife-compiler/build.gradle, butterknife-integration-test/build.gradle, butterknife-integration-test/src/test/resources/robolectric.properties, butterknife/build.gradle, butterknife/src/test/resources/robolectric.properties
@JakeWharton Update to Robolectric 3.1.2
=> Update to robolectric 3.1.2

build.gradle
@JakeWharton 
- Updated android gradle plugin 2.1.3(didn't see this before)
- Updated google android library to 4.1.1.4
- Updated support libraries to 24.2.0
=> Update support libraries 24.2.0

build.gradle, sample/app/build.gradle, sample/library/build.gradle
@JakeWharton Updated the samples to use the latest butterknife
=> Update butterknife in sample to 8.4.0

build.gradle
@ChristianBecker @JakeWharton Based on your comment here: https://github.com/JakeWharton/butterknife/pull/731#issuecomment-244960451
=> Move from support v4 to support compat 24.2.0

butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
=> Do not claim annotations in the processor.

butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java, butterknife/src/test/java/butterknife/OnTouchTest.java
=> Add SuppressLint("ClickableViewAccessibility") to OnTouchListener's

butterknife/src/test/java/butterknife/BindArrayTest.java, butterknife/src/test/java/butterknife/BindBitmapTest.java, butterknife/src/test/java/butterknife/BindBoolTest.java, butterknife/src/test/java/butterknife/BindColorTest.java, butterknife/src/test/java/butterknife/BindDimenTest.java, butterknife/src/test/java/butterknife/BindDrawableTest.java, butterknife/src/test/java/butterknife/BindFloatTest.java, butterknife/src/test/java/butterknife/BindIntTest.java, butterknife/src/test/java/butterknife/BindStringTest.java, butterknife/src/test/java/butterknife/BindViewTest.java, butterknife/src/test/java/butterknife/BindViewsTest.java, butterknife/src/test/java/butterknife/OnCheckedChangedTest.java, butterknife/src/test/java/butterknife/OnClickTest.java, butterknife/src/test/java/butterknife/OnEditorActionTest.java, butterknife/src/test/java/butterknife/OnFocusChangeTest.java, butterknife/src/test/java/butterknife/OnItemClickTest.java, butterknife/src/test/java/butterknife/OnItemLongClickTest.java, butterknife/src/test/java/butterknife/OnItemSelectedTest.java, butterknife/src/test/java/butterknife/OnLongClickTest.java, butterknife/src/test/java/butterknife/OnPageChangeTest.java, butterknife/src/test/java/butterknife/OnTextChangedTest.java, butterknife/src/test/java/butterknife/OnTouchTest.java, butterknife/src/test/java/butterknife/RClassTest.java, butterknife/src/test/java/butterknife/UnbinderTest.java
This used to be required and affect code output but it no longer does so.
=> Remove test subjects from extending Activity.

butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt
Closes #952.
If only we had integration tests...
=> Replace periods in the package name, not commas.

butterknife-annotations/src/main/java/butterknife/BindFont.java, butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldResourceBinding.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldTypefaceBinding.java, butterknife/src/test/java/butterknife/BindFontTest.java
=> Add style support to Typeface binding.

build.gradle, gradle.properties, sample/app/src/main/AndroidManifest.xml, sample/library/build.gradle, sample/library/src/main/java/com/example/butterknife/library/SimpleActivity.java, sample/library/src/main/java/com/example/butterknife/library/SimpleAdapter.java
- Add gradle-versions-plugin
- Increase Gradle daemon heap to run dex in process
- Bump some dependencies
- Suppress lint checks
- Bump support library deps
- Requires minSdk 14 or tools:overrideLibrary="android.support.compat"
=> Tidying up

build.gradle, butterknife-lint/src/main/java/butterknife/lint/InvalidR2UsageDetector.java, butterknife-lint/src/test/java/butterknife/lint/InvalidR2UsageDetectorTest.java, butterknife-lint/src/test/java/butterknife/lint/LintRegistryTest.java
Also migrates lint tests to new TestLintTask style
=> Port lint checks to UAST

butterknife-compiler/src/main/java/butterknife/compiler/FieldTypefaceBinding.java, butterknife/src/test/java/butterknife/BindFontTest.java
=> Correct @BindFont code generation pre-API 26.

butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java, butterknife/src/test/java/butterknife/BindViewTest.java
=> Emit a cast for non-View bindings in the specialized single binding case.

build.gradle
@JakeWharton 
- Update support libraries to 26.0.1
- Update android gradle plugin to 3.0.0-beta2
- Update lint to 3.0.0-beta2
- Make sure to use latest butterknife release, 8.8.1
- Update robolectric to 3.4.2
=> Update various dependencies

butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
Followup from a small regression introduced in #1075
=> Compute fq name correctly when using R2

.travis.yml
@JakeWharton 
According to the docs here: https://docs.travis-ci.com/user/languages/android/#Caching
=> Update TravisCI caching

README.md
=> Mention kapt in README.

butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt
This fixes #1124 by using a method that still exists.
=> Fix the plugin on AGP 3.1

butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java
Fixes #1254 by making the integer value lookup defensive. If R scanner fails, always fall back to raw integer literal based Ids
=> Make R symbol scanner defensive for integer value lookups

index.html
Matches Gradle usage as seen on https://github.com/JakeWharton/butterknife#download section.
=> Use 'implementation' instead of 'compile'

butterknife-annotations/src/main/java/butterknife/BindAnim.java, butterknife-annotations/src/main/java/butterknife/BindBitmap.java, butterknife-annotations/src/main/java/butterknife/BindBool.java, butterknife-annotations/src/main/java/butterknife/BindFloat.java, butterknife-annotations/src/main/java/butterknife/BindFont.java, butterknife-annotations/src/main/java/butterknife/BindInt.java, butterknife-reflect/src/main/java/butterknife/ButterKnife.java, butterknife-reflect/src/main/java/butterknife/FieldUnbinder.java
Animation, array, bitmap, boolean, color, float, font, and int.
=> Add remaining field binding to reflect

butterknife-annotations/src/main/java/butterknife/OnItemClick.java, butterknife-reflect/src/main/java/butterknife/ButterKnife.java
This makes the integration test fully functional when backed by the reflect backend.
=> Add item click to reflect

butterknife-reflect/src/main/java/butterknife/ButterKnife.java, checkstyle.xml
=> Implement crazy parameter matching in reflection

butterknife-reflect/src/main/java/butterknife/ButterKnife.java, butterknife/src/main/java/butterknife/ButterKnife.java
=> Stop search at androidx.

build.gradle, butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldResourceBinding.java, butterknife-compiler/src/main/java/butterknife/compiler/Id.java, butterknife-compiler/src/main/java/butterknife/compiler/ViewBinding.java, butterknife-reflect/src/main/java/butterknife/ButterKnife.java, butterknife-reflect/src/main/java/butterknife/CompositeUnbinder.java, butterknife-runtime/src/androidTest/java/butterknife/ViewCollectionsTest.java, butterknife-runtime/src/main/java/butterknife/Setter.java, butterknife-runtime/src/main/java/butterknife/ViewCollections.java, butterknife-runtime/src/test/java/butterknife/TestGeneratingProcessor.java, butterknife/src/androidTest/java/butterknife/ButterKnifeTest.java
=> Add error-prone and NullAway

build.gradle
=> Lower consumer AGP requirements

build.gradle, butterknife-annotations/src/main/java/butterknife/OnPageChange.java, butterknife-annotations/src/main/java/butterknife/internal/ListenerClass.java, butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java, butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldDrawableBinding.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldResourceBinding.java, butterknife-compiler/src/main/java/butterknife/compiler/FieldTypefaceBinding.java, butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt, butterknife-gradle-plugin/src/main/java/butterknife/plugin/FinalRClassBuilder.java, butterknife-gradle-plugin/src/test/java/butterknife/plugin/FinalRClassBuilderTest.kt, butterknife-gradle-plugin/src/test/resources/fixtures/R2.java
AndroidX is current. Support is legacy.
=> Invert support/androidx terminology

butterknife-annotations/build.gradle, butterknife-compiler/build.gradle, butterknife-gradle-plugin/src/test/build.gradle, butterknife-integration-test/src/main/java/com/example/butterknife/library/SimpleActivity.java, butterknife-runtime/build.gradle, butterknife-runtime/src/androidTest/java/butterknife/ViewCollectionsTest.java, butterknife-runtime/src/main/java/butterknife/Unbinder.java, butterknife-runtime/src/main/java/butterknife/internal/DebouncingOnClickListener.java, butterknife/build.gradle, butterknife/src/androidTest/java/butterknife/ButterKnifeTest.java
As promised in the RC1 release notes...
=> Make all artifacts use Java 8 bytecode

butterknife-compiler/src/main/java/butterknife/compiler/BindingSet.java
=> Work around Jetifier being a thing

butterknife-gradle-plugin/src/main/java/butterknife/plugin/FinalRClassBuilder.kt
=> Use US locale to uppercase annotation first letter

butterknife-annotations/src/main/java/butterknife/OnTextChanged.java, butterknife-reflect/src/main/java/butterknife/ButterKnife.java, butterknife-reflect/src/main/java/butterknife/EmptyTextWatcher.java, butterknife-reflect/src/main/java/butterknife/ListenerUnbinder.java, checkstyle.xml
=> Add @OnTextChanged support to reflect backend

build.gradle, butterknife-annotations/src/main/java/butterknife/OnPageChange.java, butterknife-reflect/build.gradle, butterknife-reflect/src/main/java/butterknife/ButterKnife.java
Similar to `@OnTextChanged`.
Working on `@OnItemSelected` next. I'll definitely open a PR before trying to make the implementation reusable for other listeners.
=> Add @OnPageChange support to reflect backend

butterknife-integration-test/src/androidTest/java/com/example/butterknife/functional/OnItemSelectedTest.java
I used a test double here to invoke the callbacks, since I couldn't find a reasonable way to do that using framework classes (`Spinner`/`ListView`/`GridView`).
I would appreciate your feedback.
=> @OnItemSelected integration test

README.md
=> Daggers hyperlink directs users to page that alerts user of deprecation 

build.gradle, butterknife-gradle-plugin/src/main/java/butterknife/plugin/ButterKnifePlugin.kt
=> Update to AGP 3.3 as minimum supported version

butterknife-compiler/src/main/java/butterknife/compiler/ButterKnifeProcessor.java, butterknife-integration-test/src/androidTest/java/com/example/butterknife/library/SimpleActivityTest.java, butterknife-integration-test/src/main/java/com/example/butterknife/library/SimpleActivity.java, butterknife-integration-test/src/main/java/com/example/butterknife/unbinder/G.java, butterknife-integration-test/src/main/res/layout/simple_activity.xml
Closes https://github.com/JakeWharton/butterknife/issues/1467
Try fix this bug. 
Override callback method when visit JCIdent. If JCIdent is Primitive we can detect that it's import static and it's int variable. Add some test's for this
=> fix static import and add test on it

website/index.html
=> Add deprecation notice

website/index.html
The anchor was not closed properly 🤦
=> Close link properly

README.md
=> Micro update for README.md
